language: go
sudo: false
go:
  - tip # The latest version of Go.
  - 1.8
before_install:
  - dep ensure -update
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
